//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentId { get; set; }
        public string comment1 { get; set; }
        public int commentedBy { get; set; }
        public int postId { get; set; }
        public System.DateTime commentedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
    }
}
